const int QUIT_SIGNAL = 0;
const int NO_ACTION = 1;
const int ACCEPT_ACTION = 2;
const int REJECT_ACTION = 3;
const int START_ACTION_AT_LOCATION = 4;
const int CANCEL_STARTED_ACTION_AT_LOCATION = 5;
const int FINISH_STARTED_ACTION_AT_LOCATION = 6;
const int MAX_SCREEN = 10;
